<script setup></script>

<template lang="pug">
h2(class="mb-5") Skills
div(class="grid grid-cols-3 lg:grid-cols-6 gap-5")
  Skill(skill='JavaScript')
  Skill(skill='TypeScript')
  Skill(skill='HTML')
  Skill(skill='CSS')
  Skill(skill='Node')
  Skill(skill='React')
  Skill(skill='Vue')
  Skill(skill='Vite')
  Skill(skill='Vitest')
  Skill(skill='Cypress')
  Skill(skill='Jest')
  Skill(skill='Feathers.js')
  Skill(skill='Express.js')
  Skill(skill='Nest.js')
  Skill(skill='TypeORM')
  Skill(skill='SQL')
  Skill(skill='MongoDB')
  Skill(skill='Postgres')
  Skill(skill='Graphql')
  Skill(skill='Docker')
  Skill(skill='Tailwind')
  Skill(skill='Adobe XD')
  Skill(skill='Figma')
  Skill(skill='Framer')
</template>
